CREATE TABLE IF NOT EXISTS payment_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(255) NOT NULL,
    amount DECIMAL(19,2),
    currency VARCHAR(3),
    status VARCHAR(50)
    );